### ISSUE TITLE
ERROR TypeError: this.isInitialized$.switchMap is not a function

### ISSUE THREAD

**Issue by khalid-elabbadi** [evodeck/angular-linkedin-sdk#12]
on angular 6 project that use last version of rxjs, this awsome library is not working

i gives this error : 
`
ERROR TypeError: this.isInitialized$.switchMap is not a function
    at LinkedInService.push../node_modules/angular-linkedin-sdk/src/linkedin.service.js.LinkedInService.login (linkedin.service.js:34)
    at OfferComponent.push../src/app/components/offer/offer.component.ts.OfferComponent.login (offer.component.ts:103)
    at Object.eval [as handleEvent] (OfferComponent.html:73)
    at handleEvent (core.js:9947)
    at callWithDebugContext (core.js:11040)
    at Object.debugHandleEvent [as handleEvent] (core.js:10743)
    at dispatchEvent (core.js:7406)
    at core.js:8886
    at SafeSubscriber.schedulerFn [as _next] (core.js:3397)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:195)
View_OfferComponent_5 @ OfferComponent.html:72
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:11002
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1567
dispatchEvent @ core.js:7410
(anonymous) @ core.js:8886
schedulerFn @ core.js:3397
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3377
push../node_modules/primeng/components/splitbutton/splitbutton.js.SplitButton.onDefaultButtonClick @ splitbutton.js:46
(anonymous) @ SplitButton.html:3
handleEvent @ core.js:9947
callWithDebugContext @ core.js:11040
debugHandleEvent @ core.js:10743
dispatchEvent @ core.js:7406
(anonymous) @ core.js:7850
(anonymous) @ platform-browser.js:1140
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:3645
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
OfferComponent.html:72 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 19, nodeDef: {…}, elDef: {…}, elView: {…}}
View_OfferComponent_5 @ OfferComponent.html:72
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:11002
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1572
dispatchEvent @ core.js:7410
(anonymous) @ core.js:8886
schedulerFn @ core.js:3397
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3377
push../node_modules/primeng/components/splitbutton/splitbutton.js.SplitButton.onDefaultButtonClick @ splitbutton.js:46
(anonymous) @ SplitButton.html:3
handleEvent @ core.js:9947
callWithDebugContext @ core.js:11040
debugHandleEvent @ core.js:10743
dispatchEvent @ core.js:7406
(anonymous) @ core.js:7850
(anonymous) @ platform-browser.js:1140
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:3645
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
`

**Comment by niralmunjariya** [comment]
I'm getting the same error, any solution for this problem?

**Comment by KevinMartins367** [comment]
I'm also using the angular 6, any news?

**Comment by KevinMartins367** [comment]
I localized the problem is involved with the version of RxJS, this lib is only compatible with RxJS-5.5.10. An update to version 6.x.x would be required.

**Comment by minik79** [comment]
I am very new to angular and using Linkedin login. Im getting the same error when tried  npm install angular-linkedin-sdk to load login page. 
 version details are  
Angular CLI: 6.1.2
Node: 8.11.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.2
@angular-devkit/core         0.7.2
@angular-devkit/schematics   0.7.2
@schematics/angular          0.7.2
@schematics/update           0.7.2
rxjs                         6.2.2
typescript                   2.7.2

What should  i do to implement linkedin login with angular new version. are we supposed to use the Linkedin javascriptsdk like In.Event.on to do the same..can some one pls  clarify.

**Comment by KevinMartins367** [comment]
I solved the problem, as far as I realized it was only an incompatibility with RxJS 6.x.x. I'm going to send a request for them to add in a new version but I'll upload it myself. If it is very urgent for you I suggest to get the files from the src folder (from my repository) and apply as a service to your project

https://github.com/KevinMartins367/angular-linkedin-sdk

**Comment by minik79** [comment]
Thanks a lot Kevin...

**Comment by minik79** [comment]
Is ther any way to get Authorization code and Access Token from this angular linked in sdk. or we hav to get manually through linked in api like www.linkedin.com/uas/auth/accesstoken?

**Comment by mssingh018** [comment]
> I solved the problem, as far as I realized it was only an incompatibility with RxJS 6.x.x. I'm going to send a request for them to add in a new version but I'll upload it myself. If it is very urgent for you I suggest to get the files from the src folder (from my repository) and apply as a service to your project
> 
> https://github.com/KevinMartins367/angular-linkedin-sdk

I m getting this error while using your repo 

ERROR in ./node_modules/angular-linkedin-sdk/index.ts
Module build failed: Error: /Users/manpreet/Documents/Projects/adversize-client/node_modules/angular-linkedin-sdk/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/manpreet/Documents/Projects/adversize-client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (/Users/manpreet/Documents/Projects/adversize-client/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by KevinMartins367** [comment]
Hi @mssingh018 , I did not get packaging (I did not understand how to do it yet) in case you want to use mine, put it as part of your project (services) and it probably works correctly
