### ISSUE TITLE
Library not working after upadting rxjs to latest version

### ISSUE THREAD

**Issue by Nandhan-augment** [evodeck/angular-linkedin-sdk#18]
ERROR in ./node_modules/angular-linkedin-sdk/index.ts
Module build failed: Error: /home/user/workarea/slydes/slydes_ui/node_modules/angular-linkedin-sdk/index.ts is missing from the TypeScript compilation. Please make sure it isin your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/user/workarea/slydes/slydes_ui/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:753:23)
    at plugin.done.then (/home/user/workarea/slydes/slydes_ui/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by DydjyZ** [comment]
Same.
Anyone found a solution ?
